services:
  hysteria2:
    image: tobyxdd/hysteria:v2
    container_name: hysteria2
    ports:
      - "443:443"
    volumes:
      - ./proxy/hysteria2/config.json:/root/proxy/hysteria2/config.json
      - ${LOCALCERTPATH}:${CERTPATH}
      - ${LOCALPKEYPATH}:${PKEYPATH}
    restart: unless-stopped
    command: server -c /root/proxy/hysteria2/config.json
    
  tuic:
    image: tinyserve/tuic:v1.1.2-fix1
    container_name: tuic
    ports:
      - "433:443"
    volumes:
      - ./proxy/tuic/config.json:/etc/tuic/config.json
      - ${LOCALCERTPATH}:${CERTPATH}
      - ${LOCALPKEYPATH}:${PKEYPATH}
    restart: unless-stopped
    tty: true

  shadowsocks:
    image: shadowsocks/shadowsocks-libev:v3.3.5
    container_name: shadowsocks
    ports:
      - "453:443"
    volumes:
      - ./proxy/shadowsocks/config.json:/etc/shadowsocks-libev/config.json
    restart: unless-stopped
    command: ss-server -c /etc/shadowsocks-libev/config.json

  trojan:
    image: trojangfw/trojan:latest
    container_name: trojan
    ports:
      - "463:443"
    volumes:
      - ./proxy/trojan/config.json:/config/config.json
      - ${LOCALCERTPATH}:${CERTPATH}
      - ${LOCALPKEYPATH}:${PKEYPATH}
    restart: unless-stopped
    tty: true

  juicity:
    image: ghcr.io/juicity/juicity:v0.4.3
    container_name: juicity
    ports:
      - "473:443"
    volumes:
      - ./proxy/juicity/config.json:/etc/juicity/server.json
      - ${LOCALCERTPATH}:${CERTPATH}
      - ${LOCALPKEYPATH}:${PKEYPATH}
    restart: unless-stopped
    tty: true